/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export enum MintStandard {
  MetaplexNft,
  Nifty,
}

export type MintStandardArgs = MintStandard;

export function getMintStandardEncoder(): Encoder<MintStandardArgs> {
  return getEnumEncoder(MintStandard);
}

export function getMintStandardDecoder(): Decoder<MintStandard> {
  return getEnumDecoder(MintStandard);
}

export function getMintStandardCodec(): Codec<MintStandardArgs, MintStandard> {
  return combineCodec(getMintStandardEncoder(), getMintStandardDecoder());
}
