/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export enum Tag {
  Uninitialized,
  ActiveRecord,
  InactiveRecord,
}

export type TagArgs = Tag;

export function getTagEncoder(): Encoder<TagArgs> {
  return getEnumEncoder(Tag);
}

export function getTagDecoder(): Decoder<Tag> {
  return getEnumDecoder(Tag);
}

export function getTagCodec(): Codec<TagArgs, Tag> {
  return combineCodec(getTagEncoder(), getTagDecoder());
}
